const clockList = [
    {
      "id": 1,
      "code":"A103801A1L1A1",
      "location": "./media/img/p1.jpeg",
      "title": "Classic Shinola002",
      "shipping": "Free standard domestic shipping on all orders. International shipping rates vary.",
      "return": "30-day return policy for unused and unworn items. Some exclusions apply.",
      "warranty": "Manufacturer warranty included. Terms vary by brand.",
      "lgdescription": "The Classic Shinola002 features a timeless design with stainless steel construction and a leather strap. Water-resistant up to 50 meters.",
      "button_text": "Add to cart",
      "price": "299.99",
      "type": "Quartz",
      "calber": "Ronda 5030.D",
      "caseMaterial": "Stainless steel",
      "strapMaterial": "Leather",
      "diameter": "40 mm",
      "waterResistance": "50 M",
      "crystal": "Mineral",
      "brand": "Shinola",
      "display": "Analog",
      "color": "black",
      "width": "20 mm",
      "height": "10 mm",
      "quantity": 8
    },
    {
      "id": 2,
      "code":"A103801A1L1A2",
      "location": "./media/img/p2.jpeg",
      "title": "Weekender Chronograph",
      "shipping": "Free shipping on orders over $50. Additional charges may apply for international shipping.",
      "return": "Easy 30-day returns for unused items.",
      "warranty": "1-year manufacturer warranty included.",
      "lgdescription": "The Timex Weekender Chronograph offers a blend of style and functionality with its chronograph feature and interchangeable straps.",
      "button_text": "Add to cart",
      "price": "119.99",
      "type": "Quartz",
      "calber": "Timex Chronograph",
      "caseMaterial": "Brass",
      "strapMaterial": "Nylon",
      "diameter": "42 mm",
      "waterResistance": "30 M",
      "crystal": "Mineral",
      "brand": "Timex",
      "display": "Analog",
      "color": "blue",
      "width": "20 mm",
      "height": "12 mm",
      "quantity": 10
    },
    {
      "id": 3,
      "code":"A103801A1L1A3",
      "location": "./media/img/p3.jpeg",
      "title": "Gen 5 Smartwatch",
      "shipping": "Free standard shipping on all orders.",
      "return": "30-day return policy for unworn items.",
      "warranty": "Manufacturer warranty included.",
      "lgdescription": "The Fossil Gen 5 Smartwatch blends modern technology with classic design. Features include heart rate tracking, GPS, and smartphone notifications.",
      "button_text": "Add to cart",
      "price": "299.99",
      "type": "Smartwatch",
      "calber": "Digital",
      "caseMaterial": "Stainless steel",
      "strapMaterial": "Leather",
      "diameter": "44 mm",
      "waterResistance": "30 M",
      "crystal": "Mineral",
      "brand": "Fossil",
      "display": "Digital",
      "color": "black",
      "width": "22 mm",
      "height": "13 mm",
      "quantity": 5
    },
    {
      "id": 4,
      "code":"A103801A1L1A4",
      "location": "./media/img/p4.jpeg",
      "title": "Eco-Drive Chandler",
      "shipping": "Free shipping on orders over $100. International shipping rates apply.",
      "return": "30-day return policy for unused items.",
      "warranty": "5-year manufacturer warranty included.",
      "lgdescription": "The Citizen Eco-Drive Chandler is a reliable timepiece that never needs a battery change, powered by any light source. Water-resistant up to 100 meters.",
      "button_text": "Add to cart",
      "price": "199.99",
      "type": "Solar",
      "calber": "Eco-Drive E111",
      "caseMaterial": "Stainless steel",
      "strapMaterial": "Nylon",
      "diameter": "42 mm",
      "waterResistance": "100 M",
      "crystal": "Mineral",
      "brand": "Citizen",
      "display": "Analog",
      "color": "green",
      "width": "20 mm",
      "height": "11 mm",
      "quantity": 7
    },
    {
      "id": 5,
      "code":"A103801A1L1A5",
      "location": "./media/img/p5.jpeg",
      "title": "Khaki Field Mechanical",
      "shipping": "Free standard shipping on all orders.",
      "return": "30-day return policy for unworn items.",
      "warranty": "2-year manufacturer warranty included.",
      "lgdescription": "The Hamilton Khaki Field Mechanical pays homage to military watches with its rugged design and reliable mechanical movement. Water-resistant up to 50 meters.",
      "button_text": "Add to cart",
      "price": "499.99",
      "type": "Mechanical Hand-winding",
      "calber": "ETA 2804-2",
      "caseMaterial": "Stainless steel",
      "strapMaterial": "Canvas",
      "diameter": "38 mm",
      "waterResistance": "50 M",
      "crystal": "Sapphire",
      "brand": "Hamilton",
      "display": "Analog",
      "color": "green",
      "width": "20 mm",
      "height": "12 mm",
      "quantity": 9
    },
    {
      "id": 6,
      "code":"A103801A1L1A6",
      "location": "./media/img/p6.jpeg",
      "title": "Presage Cocktail Time",
      "shipping": "Free shipping on orders over $200. International shipping rates apply.",
      "return": "Easy 30-day returns for unused items.",
      "warranty": "3-year manufacturer warranty included.",
      "lgdescription": "The Seiko Presage Cocktail Time is inspired by the art of mixology, featuring a textured dial reminiscent of a cocktail glass. Water-resistant up to 50 meters.",
      "button_text": "Add to cart",
      "price": "599.99",
      "type": "Automatic",
      "calber": "Seiko 4R35",
      "caseMaterial": "Stainless steel",
      "strapMaterial": "Leather",
      "diameter": "40 mm",
      "waterResistance": "50 M",
      "crystal": "Hardlex",
      "brand": "Seiko",
      "display": "Analog",
      "color": "blue",
      "width": "20 mm",
      "height": "11 mm",
      "quantity": 6
    },
    {
      "id": 7,
      "code":"A103801A1L1A7",
      "location": "./media/img/p7.jpeg",
      "title": "Bambino Version 5",
      "shipping": "Free standard shipping on all orders.",
      "return": "30-day return policy for unworn items.",
      "warranty": "2-year manufacturer warranty included.",
      "lgdescription": "The Orient Bambino Version 5 exudes vintage charm with its domed crystal and minimalist design. Water-resistant up to 30 meters.",
      "button_text": "Add to cart",
      "price": "249.99",
      "type": "Automatic",
      "calber": "Orient F6724",
      "caseMaterial": "Stainless steel",
      "strapMaterial": "Leather",
      "diameter": "40.5 mm",
      "waterResistance": "30 M",
      "crystal": "Mineral",
      "brand": "Orient",
      "display": "Analog",
      "color": "brown",
      "width": "21 mm",
      "height": "11 mm",
      "quantity": 8
    },
    {
      "id": 8,
      "code":"A103801A1L1A8",
      "location": "./media/img/p8.jpeg",
      "title": "G-Shock Mudmaster",
      "shipping": "Free standard shipping on all orders.",
      "return": "30-day return policy for unworn items.",
      "warranty": "1-year manufacturer warranty included.",
      "lgdescription": "The Casio G-Shock Mudmaster is designed to withstand harsh environments with its mud-resistant construction and shock absorption. Water-resistant up to 200 meters.",
      "button_text": "Add to cart",
      "price": "449.99",
      "type": "Quartz",
      "calber": "Digital",
      "caseMaterial": "Resin",
      "strapMaterial": "Resin",
      "diameter": "56 mm",
      "waterResistance": "200 M",
      "crystal": "Mineral",
      "brand": "Casio",
      "display": "Digital",
      "color": "black",
      "width": "24 mm",
      "height": "17 mm",
      "quantity": 7
    },
    {
      "id": 9,
      "code":"A103801A1L1A9",
      "location": "./media/img/p9.jpeg",
      "title": "True Thinline",
      "shipping": "Free shipping on orders over $500. International shipping rates apply.",
      "return": "Easy 30-day returns for unused items.",
      "warranty": "2-year manufacturer warranty included.",
      "lgdescription": "The Rado True Thinline impresses with its ultra-slim profile and lightweight ceramic construction. Water-resistant up to 30 meters.",
      "button_text": "Add to cart",
      "price": "1299.99",
      "type": "Quartz",
      "calber": "Rado R13761152",
      "caseMaterial": "Ceramic",
      "strapMaterial": "Ceramic",
      "diameter": "39 mm",
      "waterResistance": "30 M",
      "crystal": "Sapphire",
      "brand": "Rado",
      "display": "Analog",
      "color": "white",
      "width": "18 mm",
      "height": "5 mm",
      "quantity": 9
    },
    {
      "id": 10,
      "code":"A103801A1L1A10",
      "location": "./media/img/p10.jpeg",
      "title": "Precisionist Chronograph",
      "shipping": "Free standard shipping on all orders.",
      "return": "30-day return policy for unworn items.",
      "warranty": "3-year manufacturer warranty included.",
      "lgdescription": "The Bulova Precisionist Chronograph offers unparalleled accuracy with its high-frequency quartz movement. Water-resistant up to 100 meters.",
      "button_text": "Add to cart",
      "price": "399.99",
      "type": "Quartz",
      "calber": "Bulova 96B175",
      "caseMaterial": "Stainless steel",
      "strapMaterial": "Stainless steel",
      "diameter": "46 mm",
      "waterResistance": "100 M",
      "crystal": "Sapphire",
      "brand": "Bulova",
      "display": "Analog",
      "color": "silver",
      "width": "24 mm",
      "height": "14 mm",
      "quantity": 6
    },
    {
      "id": 11,
      "code":"A103801A1L1A11",
      "location": "./media/img/p11.jpeg",
      "title": "Le Locle Powermatic 80",
      "shipping": "Free shipping on orders over $300. International shipping rates apply.",
      "return": "30-day return policy for unworn items.",
      "warranty": "2-year manufacturer warranty included.",
      "lgdescription": "The Tissot Le Locle Powermatic 80 combines classic design with modern technology, featuring an 80-hour power reserve and Swiss-made automatic movement. Water-resistant up to 30 meters.",
      "button_text": "Add to cart",
      "price": "999.99",
      "type": "Automatic",
      "calber": "Powermatic 80.111",
      "caseMaterial": "Stainless steel",
      "strapMaterial": "Leather",
      "diameter": "39 mm",
      "waterResistance": "30 M",
      "crystal": "Sapphire",
      "brand": "Tissot",
      "display": "Analog",
      "color": "silver",
      "width": "20 mm",
      "height": "11 mm",
      "quantity": 8
    },
    {
      "id": 12,
      "code":"A103801A1L1A12",
      "location": "./media/img/p12.jpeg",
      "title": "Aquaracer Quartz",
      "shipping": "Free standard shipping on all orders.",
      "return": "30-day return policy for unworn items.",
      "warranty": "2-year manufacturer warranty included.",
      "lgdescription": "The Tag Heuer Aquaracer Quartz is built for aquatic exploration with its rugged construction and water resistance up to 300 meters.",
      "button_text": "Add to cart",
      "price": "1699.99",
      "type": "Quartz",
      "calber": "Tag Heuer Ronda 715",
      "caseMaterial": "Stainless steel",
      "strapMaterial": "Stainless steel",
      "diameter": "43 mm",
      "waterResistance": "300 M",
      "crystal": "Sapphire",
      "brand": "Tag Heuer",
      "display": "Analog",
      "color": "blue",
      "width": "22 mm",
      "height": "12 mm",
      "quantity": 7
    }
  ]
  export { clockList };